version: "3"

services:
  app:
    container_name: reactbricks_portfolio
    image: ashiqul33/portfolio:reactbricks
    build:
      dockerfile: Dockerfile.production

    # remove this option because serve with nginx
    # ports:
    #   - 3000:3000

  nginx:
    container_name: reactbricks_nginx
    image: ashiqul33/portfolio:nginx
    build: ./nginx
    ports:
      - 80:80
