services:
  ashiqul:
    container_name: ashiqul
    restart: always
    image: ashiqul33/ashiqul:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./public:/app/public
    networks:
      - ashiqul

networks:
  ashiqul:
    external: true
